### ISSUE TITLE
Help required to merge upstream

### ISSUE THREAD

**Issue by yamahito** [evolvedbinary/hsg-project-wiki#1]
Hi @joewiz as discussed on our phonecall, here is a copy of my local "forked" version of the hsg-project wiki for you to merge changes: many thanks for doing so in advance!

**Comment by joewiz** [comment]
@yamahito Thank you! I've merged your commits. https://github.com/HistoryAtState/hsg-project/wiki/social-media-cards

**Comment by yamahito** [comment]
Great, thanks!  It looks like github wiki pages don't handle footnotes so well, I'll take a look...
